### ISSUE TITLE
TypeError: Cannot read property 'profiles' of undefined

### ISSUE THREAD

**Issue by KSu42** [genderquery/netflix-migrate#9] opened 2018-08-28 02:02 UTC
I get the following error

~~~~
TypeError: Cannot read property 'profiles' of undefined
    at /Users/ksu42/.nvm/versions/node/v6.11.2/lib/node_modules/netflix-migrate/node_modules/netflix2/lib/netflix2.js:66:24
    at Request._callback (/Users/ksu42/.nvm/versions/node/v6.11.2/lib/node_modules/netflix-migrate/node_modules/netflix2/lib/netflix2.js:199:5)
    at Request.self.callback (/Users/ksu42/.nvm/versions/node/v6.11.2/lib/node_modules/netflix-migrate/node_modules/request/request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/ksu42/.nvm/versions/node/v6.11.2/lib/node_modules/netflix-migrate/node_modules/request/request.js:1161:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/ksu42/.nvm/versions/node/v6.11.2/lib/node_modules/netflix-migrate/node_modules/request/request.js:1083:12)
    at IncomingMessage.g (events.js:292:16)
~~~~

**Comment by machine1104** [comment] 2018-09-30 17:55
me too
it doesnt show my password when i insert it

**Comment by LBBO** [comment] 2018-10-15 15:05
@KSu42 I get exactly that error when I enter a wrong email or password. Please double check for typos in both. Providing them as command line arguments (e.g. `node index.js -e example@email.com -p password`) could make that easier.

@machine1104 Same goes for you. The password is hidden as a security measure. If you really want to see it, you can provide it as a command line argument as described above.

Please both let me know if this fixes your problems so I can close this issue.

**Comment by machine1104** [comment] 2018-10-15 21:33
my password has double and single quotes in it
how do i insert it with -p command?

**Comment by LBBO** [comment] 2018-10-15 21:40
I think replacing double quotes with `\"` should do the trick. Single quotes shouldn't have to be escaped, as far as I know.

**Comment by machine1104** [comment] 2018-10-15 21:42
the problem is the ")" i think

**Comment by machine1104** [comment] 2018-10-15 21:45
i use netflix-migrate --email myemail --password mypasswordwithbackslashbeforeparentesis\') --profile myprofile --export ratings.json

and it stuck in
>>

**Comment by LBBO** [comment] 2018-10-15 21:46
I tried different combinations (after adding a `console.dir` to index.js) and as you can see below, `'` is escaped automatically and `"` only needs to be escaped for the command line. Everything else needs no `\`

![image](https://user-images.githubusercontent.com/8076094/46980207-252ab480-d0d4-11e8-853a-833cf3fdd837.png)

**Comment by machine1104** [comment] 2018-10-15 21:48
Token ')' imprevisto nell'espressione o nell'istruzione.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken

**Comment by LBBO** [comment] 2018-10-15 21:57
First of all: I had a few years of Italian at school so I think it's kind of fun that you're an Italian.

Secondly: I can set up another account with a password containing `)` and try to find the error but I probably won't get to that for another few days. Until then, is there any more info about that error? Perhaps a file and line number or so?
I could also imagine this being an issue of [netflix2](https://github.com/genderquery/node-netflix2) and not netflix-migrate, so I might open an issue there then.

**Comment by machine1104** [comment] 2018-10-15 22:04
i tried on cmd and not powershell and seems working
this all to understand this is not the program im looking for ahahahah
i wanted to copy-paste a profile from an account to an other and i think your program is only for rates

back to the error: the problem is in powershell and not in ur program
sorry for the waste of time

ps yes is quite funny u studied italian

**Comment by LBBO** [comment] 2018-10-15 22:08
Yeah, copying viewing history is pretty high on my todo list though. The netflix API isn't documented, so I have no idea how soon that'll work out (if ever).

No problem! I'll wait for @KSu42's response and then (hopefully) close the issue.

**Comment by machine1104** [comment] 2018-10-15 22:09
you would save many lifes if u can manage how to copy-paste watched history
keep up the good work

**Comment by LBBO** [comment] 2018-10-28 20:54
Great!

**Closed by LBBO** 2018-10-28 20:54 UTC
